package com.fiture.entity;

import java.util.Date;

public class HasHistoryFitureKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hashistoryfiture.fitureId
     *
     * @mbggenerated
     */
    private Integer fitureid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hashistoryfiture.historyDateTime
     *
     * @mbggenerated
     */
    private Date historydatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hashistoryfiture.userId
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hashistoryfiture.fitureId
     *
     * @return the value of hashistoryfiture.fitureId
     *
     * @mbggenerated
     */
    public Integer getFitureid() {
        return fitureid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hashistoryfiture.fitureId
     *
     * @param fitureid the value for hashistoryfiture.fitureId
     *
     * @mbggenerated
     */
    public void setFitureid(Integer fitureid) {
        this.fitureid = fitureid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hashistoryfiture.historyDateTime
     *
     * @return the value of hashistoryfiture.historyDateTime
     *
     * @mbggenerated
     */
    public Date getHistorydatetime() {
        return historydatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hashistoryfiture.historyDateTime
     *
     * @param historydatetime the value for hashistoryfiture.historyDateTime
     *
     * @mbggenerated
     */
    public void setHistorydatetime(Date historydatetime) {
        this.historydatetime = historydatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hashistoryfiture.userId
     *
     * @return the value of hashistoryfiture.userId
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hashistoryfiture.userId
     *
     * @param userid the value for hashistoryfiture.userId
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
}