package com.fiture.entity;

public class HasLabelKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column haslabel.fitureId
     *
     * @mbggenerated
     */
    private Integer fitureid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column haslabel.labelId
     *
     * @mbggenerated
     */
    private Integer labelid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column haslabel.fitureId
     *
     * @return the value of haslabel.fitureId
     *
     * @mbggenerated
     */
    public Integer getFitureid() {
        return fitureid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column haslabel.fitureId
     *
     * @param fitureid the value for haslabel.fitureId
     *
     * @mbggenerated
     */
    public void setFitureid(Integer fitureid) {
        this.fitureid = fitureid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column haslabel.labelId
     *
     * @return the value of haslabel.labelId
     *
     * @mbggenerated
     */
    public Integer getLabelid() {
        return labelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column haslabel.labelId
     *
     * @param labelid the value for haslabel.labelId
     *
     * @mbggenerated
     */
    public void setLabelid(Integer labelid) {
        this.labelid = labelid;
    }

    public HasLabelKey(Integer labelId,Integer fitureId){
        this.labelid=labelId;
        this.fitureid=fitureId;
    }
}