package com.fiture.entity;

public class HasPictureKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column haspicture.authorId
     *
     * @mbggenerated
     */
    private Integer authorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column haspicture.fitureId
     *
     * @mbggenerated
     */
    private Integer fitureid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column haspicture.pictureId
     *
     * @mbggenerated
     */
    private Integer pictureid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column haspicture.authorId
     *
     * @return the value of haspicture.authorId
     *
     * @mbggenerated
     */
    public Integer getAuthorid() {
        return authorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column haspicture.authorId
     *
     * @param authorid the value for haspicture.authorId
     *
     * @mbggenerated
     */
    public void setAuthorid(Integer authorid) {
        this.authorid = authorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column haspicture.fitureId
     *
     * @return the value of haspicture.fitureId
     *
     * @mbggenerated
     */
    public Integer getFitureid() {
        return fitureid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column haspicture.fitureId
     *
     * @param fitureid the value for haspicture.fitureId
     *
     * @mbggenerated
     */
    public void setFitureid(Integer fitureid) {
        this.fitureid = fitureid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column haspicture.pictureId
     *
     * @return the value of haspicture.pictureId
     *
     * @mbggenerated
     */
    public Integer getPictureid() {
        return pictureid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column haspicture.pictureId
     *
     * @param pictureid the value for haspicture.pictureId
     *
     * @mbggenerated
     */
    public void setPictureid(Integer pictureid) {
        this.pictureid = pictureid;
    }
    public HasPictureKey(Integer authorId,Integer pictureId,Integer fitureId){
        this.authorid=authorId;
        this.fitureid=fitureId;
        this.pictureid=pictureId;
    }
}