package com.fiture.dao;

import com.fiture.entity.Fiture;

import java.util.List;

public interface FitureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fiture
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fiture
     *
     * @mbggenerated
     */
    int insert(Fiture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fiture
     *
     * @mbggenerated
     */
    int insertSelective(Fiture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fiture
     *
     * @mbggenerated
     */
    Fiture selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fiture
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Fiture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fiture
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Fiture record);

    void updateContentByPrimaryKey(int fitureId,String content);

    List selectByAuthorId(int authorId);
}