package com.fiture.dao;

import com.fiture.entity.HasHistoryFitureKey;

public interface HasHistoryFitureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hashistoryfiture
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(HasHistoryFitureKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hashistoryfiture
     *
     * @mbggenerated
     */
    int insert(HasHistoryFitureKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hashistoryfiture
     *
     * @mbggenerated
     */
    int insertSelective(HasHistoryFitureKey record);
}