package com.fiture.dao;

import com.fiture.entity.HasPictureKey;

import java.util.List;

public interface HasPictureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haspicture
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(HasPictureKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haspicture
     *
     * @mbggenerated
     */
    int insert(HasPictureKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table haspicture
     *
     * @mbggenerated
     */
    int insertSelective(HasPictureKey record);

    int selectPictureIdsByFitureId(int fitureId);

    int deleteByFitureId(int fitureId);
}